# Generated by Django 4.1.5 on 2023-01-26 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='next_watering',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 12, 41, 13, 643124)),
            preserve_default=False,
        ),
    ]
